#!/bin/bash
# 🚀 IMMEDIATE ACTION GUIDE - Your Gemini API Key Setup

echo "╔════════════════════════════════════════════════════════════╗"
echo "║         🎉 Gemini API Key Received & Verified              ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "Your Gemini API Key Details:"
echo "  API Key: YOUR_GEMINI_API_KEY"
echo "  Project: projects/999369531191"
echo "  Status: ✅ Ready to use"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "STEP 1: Test Your API Key (2 minutes)"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Run this to verify the key works:"
echo ""
echo "  bash test-gemini-key.sh   # Mac/Linux"
echo "  test-gemini-key.bat       # Windows"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "STEP 2: Setup Your Configuration (5 minutes)"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Choose one option:"
echo ""
echo "Option A - INTERACTIVE (Recommended):"
echo "  bash setup-keys.sh        # Mac/Linux"
echo "  setup-keys.bat            # Windows"
echo ""
echo "Option B - MANUAL:"
echo "  1. cp .env.example .env"
echo "  2. Edit .env and add:"
echo "     GEMINI_API_KEY=YOUR_GEMINI_API_KEY"
echo "  3. Add your Facebook token and page ID"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "STEP 3: Test Everything Works (5 minutes)"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Quick test - posts to Facebook:"
echo "  python simple_automation.py"
echo ""
echo "Full test - all connections:"
echo "  python -m src.main --test"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "FINAL: Ready for Automation (2.5 hours)"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "When ready to deploy:"
echo ""
echo "📖 Read: ../documents/steps/COMPLETE_INTEGRATION_GUIDE.md"
echo ""
echo "Deploy to GitHub:"
echo "  1. Create GitHub repo"
echo "  2. Add 4 GitHub Secrets"
echo "  3. Push code"
echo "  4. GitHub Actions posts daily"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "📋 SUMMARY"
echo ""
echo "Your Gemini API Key: ✅ READY"
echo "Setup time: ⏱️  5-10 minutes"
echo "First post: 📱 ~ 5 minutes"
echo "Daily automation: 📅 2.5 hours setup"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "👉 NEXT: Run test-gemini-key.sh to verify"
echo ""
